### ISSUE TITLE
Cookie based login will be deprecated soon. Does this library support OAuth?

### ISSUE THREAD

**Issue by clearitout** [jReddit/jReddit#114]
https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/

**Comment by sfat** [comment]
Hey @clearitout. The library doesn't support OAuth at the moment. (Did you actually went through all reddit wrappers on github to ask this question? :) )

**Comment by sfat** [comment]
closing this as duplicate of #132
