### ISSUE TITLE
OAuth2 Support / Request Restructure

### ISSUE THREAD

**Issue by snkas** [jReddit/jReddit#131]
Hi all,

I'm currently working a bit on adding OAuth2 support to the jReddit library in my free time. Development goes slow due to other affairs, both it it coming! I'm also working on vastly improving the way requests are made by the library (using a decorator pattern to add parameters). I want to add support to allow the user of the library to choose any HTTPClient/HTTPSClient they wish, such as one that do not block (e.g. one from a pooling manager). The decoupling from the Reddit-related code, and the connection code might pave the way to support Android for example (which uses URLConnection's in the latest version). My pull request will probably not support any legacy functions.

Just a small update!
I like the new logo design, perhaps remove the Java sign, and just have Snoo lean against the orange colored j?

Best regards,
S

**Comment by sfat** [comment]
Hey @snkas . Long time, no see :). Good stuff. Can we try and make few tickets with each improvement you have in mind? We might be able to split up the work and I can give a hand, if you want.

**Comment by snkas** [comment]
Yes, sounds good. I'il take a look at splitting it up in the evening and creating separate tickets for them.

**Comment by sfat** [comment]
I'll be closing this guy, if you don't mind, since we have splitted the stuff on separate tickets.
