### ISSUE TITLE
OAuth2 Support

### ISSUE THREAD

**Issue by snkas** [jReddit/jReddit#132]
Support for the OAuth2 protocol. Reddit states that usage of the OAuth2 protocol will allow you application to do twice as many requests. Furthermore, the current version of sending a username and password via HTTP is unsecure as hell.

I thought about adding a wrapper for connections, something similar to:

    HTTPClient client = new HTTPClient(); // Create your own client
    OAuth2 authorization = new OAuth2(token/code);
    RequestExecutor executor = new RequestExecutor(client, authorization);

    SubredditsGetRequest request = new SubredditsGetRequest(subreddit);
    SubredditsResponseInterpreter interpreter = new SubredditsResponseInterpreter(recursive);
    
    executor.setRequest(request, interpreter);
    InterpretedResponse parsedResponse = executor.execute();

    ... and then continue.... Just a sketch.

I'il take this one on me. I think i'il use the Apache OLTU OAuth2 project (http://mvnrepository.com/artifact/org.apache.oltu.oauth2). They have a specific parameter for Reddit, pretty neat.

**Comment by snkas** [comment]
Small update: I got the Application-only authorization working.
https://github.com/reddit/reddit/wiki/OAuth2#application-only-oauth

**Comment by snkas** [comment]
Update 2: I've implemented the HTTPClient variant, I'il commit a (somewhat stable) version somewhere next week in my own repo. It will not yet offer all functionality the current one has. I'il try to incorporate as much as the existing code as possible.

Let's get that 54% test coverage to 100% btw ;)

**Comment by snkas** [comment]
Update 3: I've finished the basis for the OAuth2 part of it all. Now I'm going to convert the most essential retrieval functionality to the new format. Perhaps also a few action ones. You can check it out in my private repository.

**Comment by snkas** [comment]
Update 4: I've added all marking actions, and implemented the comment tree. It now also supports mixed listing of both Submissions and Comments. I'm now stopping with the implementation of new features, and will focus on testing it all.

@karan @sfat @raulrene Could you perhaps review the code I've written so far? I've pushed it all to my own repository. Especially the constructions used in the examples.

Will the dependency on Apache HTTPComponents force users to need to match our version of that library? The outside addition of HTTPClient allows the user to specify any HTTPClient/URLConnection he wants, even onces that do not block (e.g. from PoolingManagers).

Second, why do we have the Apache Commons dependency? Seems unnecessary. I've commented it out.

Let me know!
- S

**Comment by sfat** [comment]
@snkas just make a pull request and we'll take a look. You can remove it if it's not used.

**Comment by snkas** [comment]
@sfat Done.

**Comment by sfat** [comment]
closing this per PR already in place.
