### ISSUE TITLE
From June 29 Reddit will enforce connecting over HTTPS. Will this affect jReddit?

### ISSUE THREAD

**Issue by Seventy7wo** [jReddit/jReddit#135]
https://www.reddit.com/r/redditdev/comments/39zje0/reddit_will_soon_only_be_available_over_https/  

Will the current version of jReddit still work after June 29?

**Comment by snkas** [comment]
Yes, yes it will. See the API endpoints:

    public static final String REDDIT_BASE_URL = "http://www.reddit.com";
https://github.com/jReddit/jReddit/blob/master/src/main/java/com/github/jreddit/utils/ApiEndpointUtils.java

I'm not sure if simply changing it to "https" will enable the extra level of security, although this SSL guide does support that statement:
http://hc.apache.org/httpclient-3.x/sslguide.html

@sfat ?

**Comment by sfat** [comment]
Tested the https, seems to be alright so far. Will wait for your OAuth2 changes, @snkas. Closing this guy
