### ISSUE TITLE
Logging using slf4j + logback

### ISSUE THREAD

**Issue by sfat** [jReddit/jReddit#137]
Make use of slf4j instead of making use of ```System.out.println```.

**Comment by snkas** [comment]
Added it to the current OAuth2 build.

**Comment by sfat** [comment]
@snkas have you also removed all ```System.out.*``` out of the equation ? :hamster:

**Comment by snkas** [comment]
@sfat Yes - all, except the ones in the examples.

**Comment by sfat** [comment]
nice job. Thanks! :+1:
