### ISSUE TITLE
How to loop through every Reply of a Comment? 

### ISSUE THREAD

**Issue by pongo1231** [jReddit/jReddit#142]
I haven't found the function to get all replies on a comment yet, only the direct replies to the comment. Is there a function for that or is it a missing thing?

**Comment by snkas** [comment]
Hello!

You can retrieve replies to a comment using the FullSubmissionRequest:
https://github.com/jReddit/jReddit/blob/master/src/main/java/com/github/jreddit/request/retrieval/mixed/FullSubmissionRequest.java

Use the setComment() function to set the target, setDepth() to 8 to get the maximum depth possible, setShowMore() to true, setContext() to 0 (assuming you do not want to retrieve its parents), and limit to 500 (which is the max).

Now you have the maximum amount of replies you can get in one go. This will be parsed into a CommentTree using FullSubmissionParser:
https://github.com/jReddit/jReddit/blob/master/src/main/java/com/github/jreddit/parser/single/FullSubmissionParser.java

This comment tree will (in most cases) only contain comments. However, it can also contain More entities. These hide additional comments. They can be retrieved using MoreCommentsRequest:
https://github.com/jReddit/jReddit/blob/master/src/main/java/com/github/jreddit/request/retrieval/comments/MoreCommentsRequest.java

MoreCommentsRequest can be parsed using the CommentsMoreListing parser:
https://github.com/jReddit/jReddit/blob/master/src/main/java/com/github/jreddit/parser/listing/CommentsListingParser.java

These more comments will however *not* be in a CommentTree, but in a listing. Using the parent identifiers you could however recreate the listing. Iterate over the More's until there are none left. Maybe use a Set to filter out duplicate comments. That's it.

**Comment by pongo1231** [comment]
Thanks, I'm gonna try it out.
