### ISSUE TITLE
https access and some error handling on failed login

### ISSUE THREAD

**Issue by gregbarton** [jReddit/jReddit#99]
index 88c9761..e619bd9 100755
--- a/src/main/java/com/github/jreddit/utils/ApiEndpointUtils.java
+++ b/src/main/java/com/github/jreddit/utils/ApiEndpointUtils.java
@@ -8,7 +8,7 @@ package com.github.jreddit.utils;
  */
 public class ApiEndpointUtils {
 
-    public static final String REDDIT_BASE_URL = "http://www.reddit.com";
+    public static final String REDDIT_BASE_URL = "https://www.reddit.com";
 
     public static final String REDDIT_BASE_API_ENDPOINT = "/api";
 
~/Documents/git/jReddit: git diff 
diff --git a/src/main/java/com/github/jreddit/entity/User.java b/src/main/java/com/github/jreddit/entity/User.java
index 0d53ad5..cf08f5a 100644
--- a/src/main/java/com/github/jreddit/entity/User.java
+++ b/src/main/java/com/github/jreddit/entity/User.java
@@ -100,10 +100,13 @@ public class User {
         ArrayList<String> values = new ArrayList<String>();
         JSONObject jsonObject = (JSONObject) restClient.post("api_type=json&user=" + username + "&passwd=" + password, String.format(ApiEndpointUtils.USER_LOGIN, username), getCookie()).getResponseObject();
         JSONObject valuePair = (JSONObject) ((JSONObject) jsonObject.get("json")).get("data");
-
-        values.add(valuePair.get("modhash").toString());
-        values.add(valuePair.get("cookie").toString());
-
+        if(valuePair == null) {
+            JSONObject errors = (JSONObject) ((JSONObject) jsonObject.get("json")).get("errors");
+            throw new RuntimeException(errors.toJSONString());
+        } else {
+            values.add(valuePair.get("modhash").toString());
+            values.add(valuePair.get("cookie").toString());
+        }
         return values;
     }
 
diff --git a/src/main/java/com/github/jreddit/utils/ApiEndpointUtils.java b/src/main/java/com/github/jreddit/utils/ApiEndpointUtils.java
index 88c9761..e619bd9 100755
--- a/src/main/java/com/github/jreddit/utils/ApiEndpointUtils.java
+++ b/src/main/java/com/github/jreddit/utils/ApiEndpointUtils.java
@@ -8,7 +8,7 @@ package com.github.jreddit.utils;
  */
 public class ApiEndpointUtils {
 
-    public static final String REDDIT_BASE_URL = "http://www.reddit.com";
+    public static final String REDDIT_BASE_URL = "https://www.reddit.com";
 
     public static final String REDDIT_BASE_API_ENDPOINT = "/api";

**Comment by sfat** [comment]
@gregbarton is this supposed to be a change to the project? If the answer is yes, can you make instead a pull request with these changes?

**Comment by sfat** [comment]
I'm will close this, as I can't do anything with that code thrown as a comment. If you wish to make a PR, I'll be happily merge it.
